/**
 * Стили для страницы лидерборда
 */

export const styles = {
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "16px",
    marginBottom: "24px",
  },
  title: {
    fontSize: "28px",
    fontWeight: 700,
    margin: 0,
    display: "flex",
    alignItems: "center",
  },
  periodSelector: {
    display: "flex",
    gap: "8px",
  },
  periodButton: {
    padding: "8px 18px",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.2s",
    border: "1px solid",
  },
  chartCard: {
    padding: "20px",
    borderRadius: "12px",
    background: "var(--nt-surface, #ffffff)",
    border: "1px solid var(--nt-border-light, #f0f0f0)",
    marginBottom: "20px",
  },
  chartTitle: {
    fontSize: "16px",
    fontWeight: 600,
    marginTop: 0,
    marginBottom: "16px",
    color: "var(--nt-text, #333)",
  },
  tableCard: {
    borderRadius: "12px",
    background: "var(--nt-surface, #ffffff)",
    border: "1px solid var(--nt-border-light, #f0f0f0)",
    overflow: "hidden",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHeader: {
    background: "var(--nt-background-secondary, #f5f5f5)",
  },
  th: {
    padding: "14px 16px",
    textAlign: "left",
    fontSize: "13px",
    fontWeight: 600,
    color: "var(--nt-text-secondary, #666)",
    borderBottom: "1px solid var(--nt-border, #e0e0e0)",
  },
  rankCol: { width: "50px" },
  nameCol: { flex: 1 },
  cardsCol: { width: "100px", textAlign: "center" },
  streakCol: { width: "90px", textAlign: "center" },
  timeCol: { width: "110px", textAlign: "center" },
  td: {
    padding: "12px 16px",
    fontSize: "14px",
    borderBottom: "1px solid var(--nt-border-light, #f0f0f0)",
  },
  nameCell: { fontWeight: 500 },
  cardsCell: { textAlign: "center", fontWeight: 600 },
  streakCell: { textAlign: "center" },
  timeCell: { textAlign: "center", color: "var(--nt-text-secondary, #666)" },
  medalBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    fontWeight: 700,
    fontSize: "14px",
  },
  rankText: {
    fontSize: "14px",
    fontWeight: 600,
  },
  currentUserBadge: {
    marginLeft: "8px",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: 600,
    background: "var(--nt-primary, #667eea)",
    color: "#fff",
  },
  streakBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "2px",
    fontWeight: 600,
  },
  yourRankCard: {
    marginTop: "20px",
    padding: "16px 20px",
    borderRadius: "12px",
    background: "var(--nt-surface, #ffffff)",
    border: "1px solid var(--nt-border-light, #f0f0f0)",
    fontSize: "15px",
    display: "flex",
    alignItems: "center",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
  },
  loadingContainer: {
    textAlign: "center",
    padding: "60px 20px",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "3px solid var(--nt-border, #e0e0e0)",
    borderTopColor: "var(--nt-primary, #667eea)",
    borderRadius: "50%",
    margin: "0 auto 16px",
    animation: "spin 1s linear infinite",
  },
  errorContainer: {
    textAlign: "center",
    padding: "60px 20px",
  },
  retryButton: {
    padding: "10px 24px",
    borderRadius: "8px",
    border: "none",
    background: "var(--nt-primary, #667eea)",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    marginTop: "12px",
  },
};
