/**
 * Маппинг иконок FontAwesome для замены эмодзи
 * Разделено по категориям для лучшей организации
 */

import {
  faGraduationCap,
  faLanguage,
  faBook,
  faBookOpen,
  faPen,
  faClipboard,
  faPlay,
  faRotateRight,
  faRepeat,
  faRefresh,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faSearch,
  faDownload,
  faUpload,
  faHome,
  faChartBar,
  faChartLine,
  faList,
  faCalendar,
  faClock,
  faHourglassHalf,
  faUser,
  faUsers,
  faUserPlus,
  faAddressCard,
  faCircleUser,
  faGear,
  faPalette,
  faSliders,
  faDumbbell,
  faBrain,
  faBolt,
  faFire,
  faTrophy,
  faMedal,
  faAward,
  faStar,
  faBullseye,
  faLayerGroup,
  faClone,
  faCopy,
  faFile,
  faCircleCheck,
  faCircleXmark,
  faCircleExclamation,
  faCircleInfo,
  faEnvelope,
  faComment,
  faShare,
  faLock,
  faKey,
  faFolder,
  faFolderOpen,
  faFileText,
  faHeart,
  faMoon,
  faSun,
  faLightbulb,
  faRocket,
  faFlag,
  faBookmark,
  faLink,
  faArrowRight,
  faArrowLeft,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faEllipsis,
  faBars,
  faXmark,
  faQuestion,
  faGlobe,
  faPowerOff,
  faEdit,
  faTrash,
  faSave,
  faImage,
  faMusic,
  faStar as faStarOutline,
  faHeart as faHeartOutline,
  faClock as faClockOutline,
  faCalendar as faCalendarOutline,
  faUser as faUserOutline,
  faCircleCheck as faCircleCheckOutline,
  faRoute,
  faHeadphones,
  faPuzzlePiece,
  faFilePdf,
  faComments,
  faCalendarWeek,
  faCheckDouble,
  faUserCheck,
  faKeyboard,
  faArrowsLeftRight,
  faUserFriends,
  faStopwatch,
  faChartColumn,
  faBan,
  faEye,
  faPaperPlane,
  faShieldHalved,
  faLaptop,
  faMobile,
  faQuoteLeft,
  faCalendarCheck,
  faFireAlt,
  faSmile,
  faEllipsisV,
  faThumbtack,
  faReply,
  faWifi,
  faCircleNotch,
  faDesktop,
  faTableColumns,
} from "./imports";

// Основной набор для маппинга
export const icons = {
  // Образование
  graduationCap: faGraduationCap,
  language: faLanguage,
  book: faBook,
  bookOpen: faBookOpen,
  pen: faPen,
  clipboard: faClipboard,

  // Действия
  play: faPlay,
  rotateRight: faRotateRight,
  repeat: faRepeat,
  refresh: faRefresh,
  plus: faPlus,
  minus: faMinus,
  check: faCheck,
  times: faTimes,
  search: faSearch,
  download: faDownload,
  upload: faUpload,

  // Навигация
  home: faHome,
  chartBar: faChartBar,
  chartLine: faChartLine,
  list: faList,
  calendar: faCalendar,
  clock: faClock,
  hourglass: faHourglassHalf,

  // Пользователь
  user: faUser,
  users: faUsers,
  userPlus: faUserPlus,
  addressCard: faAddressCard,
  circleUser: faCircleUser,

  // Настройки
  gear: faGear,
  palette: faPalette,
  sliders: faSliders,

  // Тренировки
  dumbbell: faDumbbell,
  brain: faBrain,
  bolt: faBolt,
  fire: faFire,
  trophy: faTrophy,
  medal: faMedal,
  award: faAward,
  star: faStar,
  bullseye: faBullseye,

  // Карточки
  layerGroup: faLayerGroup,
  clone: faClone,
  copy: faCopy,
  file: faFile,

  // Статус
  circleCheck: faCircleCheck,
  circleXmark: faCircleXmark,
  circleExclamation: faCircleExclamation,
  circleInfo: faCircleInfo,

  // Связь
  envelope: faEnvelope,
  comment: faComment,
  share: faShare,

  // Безопасность
  lock: faLock,
  key: faKey,

  // Файлы
  folder: faFolder,
  folderOpen: faFolderOpen,
  fileText: faFileText,

  // Прочее
  heart: faHeart,
  moon: faMoon,
  sun: faSun,
  lightbulb: faLightbulb,
  rocket: faRocket,
  flag: faFlag,
  bookmark: faBookmark,
  link: faLink,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  chevronDown: faChevronDown,
  ellipsis: faEllipsis,
  bars: faBars,
  xmark: faXmark,
  question: faQuestion,
  globe: faGlobe,
  powerOff: faPowerOff,
  edit: faEdit,
  trash: faTrash,
  save: faSave,
  image: faImage,
  music: faMusic,

  // Regular (контурные)
  starOutline: faStarOutline,
  heartOutline: faHeartOutline,
  clockOutline: faClockOutline,
  calendarOutline: faCalendarOutline,
  userOutline: faUserOutline,
  checkCircleOutline: faCircleCheckOutline,

  // Новые режимы
  route: faRoute,
  headphones: faHeadphones,
  puzzlePiece: faPuzzlePiece,
  filePdf: faFilePdf,

  // Чат и статистика
  comments: faComments,
  calendarWeek: faCalendarWeek,
  checkDouble: faCheckDouble,
  userCheck: faUserCheck,
  keyboard: faKeyboard,
  arrowsLeftRight: faArrowsLeftRight,
  userFriends: faUserFriends,
  stopwatch: faStopwatch,
  chartColumn: faChartColumn,
  ban: faBan,
  eye: faEye,
  paperPlane: faPaperPlane,
  shieldHalved: faShieldHalved,
  laptop: faLaptop,
  mobile: faMobile,
  quoteLeft: faQuoteLeft,
  calendarCheck: faCalendarCheck,
  fireAlt: faFireAlt,
  smile: faSmile,
  ellipsisV: faEllipsisV,
  thumbtack: faThumbtack,
  reply: faReply,
  wifi: faWifi,
  circleNotch: faCircleNotch,
  desktop: faDesktop,
  tableColumns: faTableColumns,
};
